package tn.hunterViews.domain;

import java.util.Date;

import javax.persistence.Entity;

/**
 * Certifications generated by hbm2java
 */
@Entity
public class Certification {

	private int id;
	private User user;
	private int centre;
	private Date dateEnd;
	private Date dateStart;
	private String title;

	public Certification() {
	}
	
	

	public Certification(int centre, Date dateEnd, Date dateStart, String title) {
		this.centre = centre;
		this.dateEnd = dateEnd;
		this.dateStart = dateStart;
		this.title = title;
	}
	

	public Certification(int id, User user, int centre, Date dateEnd, Date dateStart, String title) {
		super();
		this.id = id;
		this.user = user;
		this.centre = centre;
		this.dateEnd = dateEnd;
		this.dateStart = dateStart;
		this.title = title;
	}



	public Certification(User user, int centre, Date dateEnd, Date dateStart, String title) {
		this.user = user;
		this.centre = centre;
		this.dateEnd = dateEnd;
		this.dateStart = dateStart;
		this.title = title;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public int getCentre() {
		return this.centre;
	}

	public void setCentre(int centre) {
		this.centre = centre;
	}

		public Date getDateEnd() {
		return this.dateEnd;
	}

	public void setDateEnd(Date dateEnd) {
		this.dateEnd = dateEnd;
	}
	public Date getDateStart() {
		return this.dateStart;
	}

	public void setDateStart(Date dateStart) {
		this.dateStart = dateStart;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
