package tn.hunterViews.domain;

import javax.persistence.Entity;

/**
 * Coordinates generated by hbm2java
 */
@Entity
public class Coordinates  {

	private Integer id;
	private float lat;
	private float lon;

	public Coordinates() {
	}

	public Coordinates(float lat, float lon) {
		this.lat = lat;
		this.lon = lon;
	}

		public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public float getLat() {
		return this.lat;
	}

	public void setLat(float lat) {
		this.lat = lat;
	}

	public float getLon() {
		return this.lon;
	}

	public void setLon(float lon) {
		this.lon = lon;
	}

}
