package tn.hunterViews.domain;

import java.util.Date;
import javax.persistence.Entity;

/**
 * Evaluations generated by hbm2java
 */
@Entity
public class Evaluations  {

	private Integer id;
	private Offer offers;
	private Date date;
	private float mark;

	public Evaluations() {
	}

	public Evaluations(Date date, float mark) {
		this.date = date;
		this.mark = mark;
	}

	public Evaluations(Offer offers, Date date, float mark) {
		this.offers = offers;
		this.date = date;
		this.mark = mark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	public Offer getOffers() {
		return this.offers;
	}

	public void setOffers(Offer offers) {
		this.offers = offers;
	}
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public float getMark() {
		return this.mark;
	}

	public void setMark(float mark) {
		this.mark = mark;
	}

}
