package tn.hunterViews.domain;

import java.util.Date;
import javax.persistence.Entity;



/**
 * Notifications generated by hbm2java
 */
@Entity
public class Notifications {

	private int id;
	private User user;
	private String date;
	private boolean seen;
	
	@Override
	public String toString() {
		return "Notifications [id=" + id + ", user=" + user + ", date=" + date + ", seen=" + seen + ", type=" + type
				+ ", userid=" + userid + "]";
	}

	private int type;
	private int userid;

	public int getUserid() {
		return userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public Notifications(int id, String date, int type, boolean seen, int userid, User user) {
		super();
		this.id = id;
		this.user = user;
		this.date = date;
		this.seen = seen;
		this.type = type;
		this.userid = userid;
	}

	public Notifications() {
	}

	public Notifications(String date, boolean seen, int type) {
		this.date = date;
		this.seen = seen;
		this.type = type;
	}

	public Notifications(User user, String date, boolean seen, int type) {
		this.user = user;
		this.date = date;
		this.seen = seen;
		this.type = type;
	}
	
	public Notifications(int id, User user, String date, boolean seen, int type) {
		this.id = id;
		this.user = user;
		this.date = date;
		this.seen = seen;
		this.type = type;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public boolean isSeen() {
		return this.seen;
	}

	public void setSeen(boolean seen) {
		this.seen = seen;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

}
