package tn.hunterViews.domain;

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Entity;

/**
 * Posts generated by hbm2java
 */
@Entity
public class Post  {

	private Integer id;
	private Offer Offer;
	private User user;
	private String date;
	private String description;
	private List<Reclamations> reclamationses ;
	private int userid;
	private int offerid;
	
	

	public Post(Integer id, String date, String description,
			int userid, int offerid) {
		super();
		this.id = id;
		

		this.date = date;
		this.description = description;
		
		this.userid = userid;
		this.offerid = offerid;
	}

	public Post(Integer id, tn.hunterViews.domain.Offer offer, User user, String date, String description, int userid,
			int offerid) {
		super();
		this.id = id;
		Offer = offer;
		this.user = user;
		this.date = date;
		this.description = description;
		this.userid = userid;
		this.offerid = offerid;
	}

	public int getOfferid() {
		return offerid;
	}

	public void setOfferid(int offerid) {
		this.offerid = offerid;
	}

	public Post(Integer id, tn.hunterViews.domain.Offer offer, User user, String date, String description,
			List<Reclamations> reclamationses, int userid) {
		super();
		this.id = id;
		Offer = offer;
		this.user = user;
		this.date = date;
		this.description = description;
		this.reclamationses = reclamationses;
		this.userid = userid;
	}

	public int getUserid() {
		return userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public Post() {
	}

	public Post(String date, String description) {
		this.date = date;
		this.description = description;
	}

	public Post(Offer Offer, User user, String date, String description, List<Reclamations> reclamationses) {
		this.Offer = Offer;
		this.user = user;
		this.date = date;
		this.description = description;
		this.reclamationses = reclamationses;
	}

	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}


	public Offer getOffer() {
		return this.Offer;
	}

	public void setOffer(Offer Offer) {
		this.Offer = Offer;
	}


	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public List<Reclamations> getReclamationses() {
		return this.reclamationses;
	}

	public void setReclamationses(List<Reclamations> reclamationses) {
		this.reclamationses = reclamationses;
	}

}
