package tn.hunterViews.domain;

import javax.persistence.Entity;

/**
 * Reclamations generated by hbm2java
 */
@Entity
public class Reclamations {

	private Integer id;
	private Offer offers;
	private Post posts;
	private User user;
	private String description;
	private boolean state;

	public Reclamations() {
	}

	public Reclamations(String description, boolean state) {
		this.description = description;
		this.state = state;
	}

	public Reclamations(Offer offers, Post posts, User user, String description, boolean state) {
		this.offers = offers;
		this.posts = posts;
		this.user = user;
		this.description = description;
		this.state = state;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	public Offer getOffers() {
		return this.offers;
	}

	public void setOffers(Offer offers) {
		this.offers = offers;
	}

	
	public Post getPosts() {
		return this.posts;
	}

	public void setPosts(Post posts) {
		this.posts = posts;
	}

	
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public boolean isState() {
		return this.state;
	}

	public void setState(boolean state) {
		this.state = state;
	}

}
