package tn.hunterViews.domain;
// Generated Apr 9, 2017 11:16:58 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Entity;

/**
 * Skills generated by hbm2java
 */
@Entity
public class Skills  {

	private Integer id;
	private User user;
	private int category;
	private String name;

	public Skills() {
	}

	public Skills(int category, String name) {
		this.category = category;
		this.name = name;
	}

	public Skills(User user, int category, String name) {
		this.user = user;
		this.category = category;
		this.name = name;
	}

		public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public int getCategory() {
		return this.category;
	}

	public void setCategory(int category) {
		this.category = category;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
