package tn.hunterViews.domain;
// Generated Apr 9, 2017 11:16:58 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Entity;

/**
 * User generated by hbm2java
 */
@Entity
public class User {

	private Integer id;
	private Date birthDate;
	private String city;
	private String country;
	private Date dateCreationAccount;
	private String email;
	private String firstName;
	private String image;
	private String lastName;
	private String login;
	private String password;
	private int postalCode;
	private String state;
	private int stateAccount;
	private String street;
	private Set<Certification> certificationses = new HashSet<Certification>(0);
	private Set<Skills> skillses = new HashSet<Skills>(0);
	private Set<Reclamations> reclamationses = new HashSet<Reclamations>(0);
	private Set<Offer> offerses = new HashSet<Offer>(0);
	private Set<Notifications> notificationses = new HashSet<Notifications>(0);
	private Set<Formations> formationses = new HashSet<Formations>(0);
	private List<Post> postses ;

	public User() {
	}

	public User(Date birthDate, Date dateCreationAccount, int postalCode, int stateAccount) {
		this.birthDate = birthDate;
		this.dateCreationAccount = dateCreationAccount;
		this.postalCode = postalCode;
		this.stateAccount = stateAccount;
	}

	public User(Date birthDate, String city, String country, Date dateCreationAccount, String email, String firstName,
			String image, String lastName, String login, String password, int postalCode, String state,
			int stateAccount, String street, Set<Certification> certificationses, Set<Skills> skillses,
			Set<Reclamations> reclamationses, Set<Offer> offerses, Set<Notifications> notificationses,
			Set<Formations> formationses, List<Post> postses) {
		this.birthDate = birthDate;
		this.city = city;
		this.country = country;
		this.dateCreationAccount = dateCreationAccount;
		this.email = email;
		this.firstName = firstName;
		this.image = image;
		this.lastName = lastName;
		this.login = login;
		this.password = password;
		this.postalCode = postalCode;
		this.state = state;
		this.stateAccount = stateAccount;
		this.street = street;
		this.certificationses = certificationses;
		this.skillses = skillses;
		this.reclamationses = reclamationses;
		this.offerses = offerses;
		this.notificationses = notificationses;
		this.formationses = formationses;
		this.postses = postses;
	}


	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

		public Date getDateCreationAccount() {
		return this.dateCreationAccount;
	}

	public void setDateCreationAccount(Date dateCreationAccount) {
		this.dateCreationAccount = dateCreationAccount;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public int getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(int postalCode) {
		this.postalCode = postalCode;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public int getStateAccount() {
		return this.stateAccount;
	}

	public void setStateAccount(int stateAccount) {
		this.stateAccount = stateAccount;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public Set<Certification> getCertificationses() {
		return this.certificationses;
	}

	public void setCertificationses(Set<Certification> certificationses) {
		this.certificationses = certificationses;
	}

	public Set<Skills> getSkillses() {
		return this.skillses;
	}

	public void setSkillses(Set<Skills> skillses) {
		this.skillses = skillses;
	}

	public Set<Reclamations> getReclamationses() {
		return this.reclamationses;
	}

	public void setReclamationses(Set<Reclamations> reclamationses) {
		this.reclamationses = reclamationses;
	}

	public Set<Offer> getOfferses() {
		return this.offerses;
	}

	public void setOfferses(Set<Offer> offerses) {
		this.offerses = offerses;
	}

	public Set<Notifications> getNotificationses() {
		return this.notificationses;
	}

	public void setNotificationses(Set<Notifications> notificationses) {
		this.notificationses = notificationses;
	}

	public Set<Formations> getFormationses() {
		return this.formationses;
	}

	public void setFormationses(Set<Formations> formationses) {
		this.formationses = formationses;
	}

	public List<Post> getPostses() {
		return this.postses;
	}

	public void setPostses(List<Post> postses) {
		this.postses = postses;
	}

}
